### ISSUE TITLE
Property or method is not defined on the instance but referenced during render

### ISSUE THREAD

**Issue by Shoroh** [kuroda/vue-data-scooper#1]
Dear Tsutomu Kuroda,

This is a great tool for all of us who work with Ruby on Rails, thank you very much!
I tried to implement it on my new project and have some error, could you please take a look?

```console
[Vue warn]: Property or method "name" is not defined on the instance but referenced during render. Make sure to declare reactive data properties in the data option.
```

I created a really simple form using rails-slim template:
```slim
= bootstrap_form_for @account do |f|
  = f.text_field :name, 'v-model': 'account.name'
  = f.primary 'Create Account'
= javascript_pack_tag 'hello_vue'
```

It gives me an input field we need to use with VueJs:
```html
<input v-model="account.name" type="text" name="account[name]" id="account_name" class="form-control">
```

And typical Vue JS App:
```es6
import Vue from 'vue/dist/vue.esm'
import TurbolinksAdapter from '../utilities/vue-turbolinks-adapter'
import VueDataScooper from "vue-data-scooper"
Vue.use(VueDataScooper)

document.addEventListener('turbolinks:load', () => {
  var element = document.getElementById('new_account')
  if (element != null) {

    var accountName = new Vue({
      el: '#new_account'
   })
...
```

But it doesn't work :(

**Comment by kuroda** [comment]
@Shoroh Reproduced. I will see this issue more closely later. Thanks.

**Comment by kuroda** [comment]
@Shoroh I thought that I have reproduced your problem, but it was my misunderstanding.

I installed `bootstrap_form` gem and constructed a similar app as yours, then I found that it worked correctly.

Could you give me a whole source code of you app?

----

Have you tried to replace `'turbolinks:load'` with `'DOMContentLoaded'`?

**Comment by kuroda** [comment]
@Shoroh Please clone https://github.com/oiax/tamachi_vue and checkout the `bootstrap_form_for` branch.

After setting up the app (including `bin/rake db:setup`), open http://localhost:3000//users/1/edit. 

In my environment, I don't see any error nor warning.

**Comment by Shoroh** [comment]
@kuroda Thank you for the example, I found my mistake :)

Everything works perfect!
I just forgot to change variables names. Before I used vue-data-scoper the variables in the page looked like that:

```slim
...
... 'v-model': 'name'
...
p[v-show="name"] Test!
```

Then I changed the variable by adding the scope 'account' in the form:

```slim
...
... 'v-model': 'account.name'
...
p[v-show="name"] Test! // This was the error message!
```

Thank you one more time, let's close the issue! :)
